import json
import datetime
import uuid

def generate_fhir_bundle(patient_age, visit_type, analysis_text, mcq_responses=None):
    """
    Generates a high-fidelity HL7 FHIR Bundle (JSON) containing:
    1. ClinicalImpression (Structured discrepancies)
    2. RiskAssessment (Qualitative risk)
    3. ServiceRequest (Recommended follow-up actions)
    4. Observations (Structured MCQ responses)
    Uses SNOMED-CT coding for clinical terminology.
    """
    bundle_id = str(uuid.uuid4())
    timestamp = datetime.datetime.utcnow().isoformat() + "Z"
    
    # SNOMED-CT Mappings for TruthShield Categories
    SNOMED_MAP = {
        "Mental Health": {"code": "429189000", "display": "Suicidal ideation"},
        "Substance Use": {"code": "160573003", "display": "Alcohol intake"},
        "Medication Adherence": {"code": "418635001", "display": "Non-adherence to drug treatment"},
        "Diversion": {"code": "401131006", "display": "Drug diversion"},
        "Physical Safety": {"code": "442438006", "display": "Victim of intimate partner violence"}
    }
    
    # Extract severity and counts (Robust detection)
    analysis_upper = analysis_text.upper()
    critical_count = analysis_upper.count("CRITICAL") + analysis_text.count("🔴")
    high_count = analysis_upper.count("HIGH") + analysis_text.count("🟡") + analysis_text.count("🟠")
    
    # Determine primary SNOMED code based on text analysis
    primary_code = "722742002" # Default: Discussion about health
    primary_display = "Clinical discrepancy detected"
    
    # Keyword-to-SNOMED mapping (expanded for robustness)
    for cat, info in SNOMED_MAP.items():
        if cat.lower() in analysis_text.lower():
            primary_code = info["code"]
            primary_display = info["display"]
            break
    
    entries = [
        {
            "fullUrl": f"urn:uuid:{str(uuid.uuid4())}",
            "resource": {
                "resourceType": "ClinicalImpression",
                "status": "completed",
                "code": {
                    "coding": [{"system": "http://snomed.info/sct", "code": primary_code, "display": primary_display}]
                },
                "description": "TruthShield Discrepancy Analysis",
                "subject": {"display": f"Patient (Age: {patient_age})"},
                "effectiveDateTime": timestamp,
                "summary": analysis_text,
                "note": [{"text": "Generated by MedGemma-4B (Offline/On-Device)"}]
            }
        },
        {
            "fullUrl": f"urn:uuid:{str(uuid.uuid4())}",
            "resource": {
                "resourceType": "RiskAssessment",
                "status": "final",
                "subject": {"display": f"Patient (Age: {patient_age})"},
                "occurrenceDateTime": timestamp,
                "note": [{"text": f"Found {critical_count} critical and {high_count} high-risk discrepancies."}],
                "prediction": [
                    {
                        "outcome": {"text": "Clinical Discrepancy / Concealment Risk"},
                        "qualitativeRisk": {"text": "High" if (critical_count + high_count) > 0 else "Low"}
                    }
                ]
            }
        },
        {
            "fullUrl": f"urn:uuid:{str(uuid.uuid4())}",
            "resource": {
                "resourceType": "ServiceRequest",
                "status": "active",
                "intent": "plan",
                "category": [{"coding": [{"system": "http://snomed.info/sct", "code": "410606002", "display": "Social service procedure"}]}],
                "priority": "urgent" if critical_count > 0 else "routine",
                "code": {"text": "In-depth clinical reconciliation and safety assessment"},
                "subject": {"display": f"Patient (Age: {patient_age})"},
                "reasonCode": [{"text": f"Detected {primary_display}"}]
            }
        }
    ]

    # Add MCQ Observations if provided
    if mcq_responses:
        from questions import PATIENT_MCQS
        for i, val in enumerate(mcq_responses):
            if i < len(PATIENT_MCQS):
                q = PATIENT_MCQS[i]
                entries.append({
                    "fullUrl": f"urn:uuid:{str(uuid.uuid4())}",
                    "resource": {
                        "resourceType": "Observation",
                        "status": "final",
                        "code": {"text": q["question"]},
                        "valueString": val if val else "No response",
                        "subject": {"display": f"Patient (Age: {patient_age})"},
                        "effectiveDateTime": timestamp,
                        "category": [{"coding": [{"system": "http://snomed.info/sct", "code": "273586006", "display": "Master questionnaire"}]}]
                    }
                })

    bundle = {
        "resourceType": "Bundle",
        "id": bundle_id,
        "type": "collection",
        "timestamp": timestamp,
        "entry": entries
    }
    
    return json.dumps(bundle, indent=2)

def generate_api_curl_sample(server_url="http://localhost:7860"):
    """Returns a sample CURL command for hospital developers to integrate."""
    return f"""# Sample Hospital EHR Integration Call
curl -X POST {server_url}/api/predict \\
  -H "Content-Type: application/json" \\
  -d '{{
    "data": [
      "Patient reports daily alcohol use in survey...", 
      "Clinician documents social drinking only...",
      "45",
      "Routine Follow-up",
      "Alcohol Misuse"
    ]
  }}'"""
